name: Build and Deploy

on:
  push:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Send Discord webhook message
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          username: Compatibility List Update
          color: "#33b5e5"
          avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
          description: A new update for the compatibility list will be deployed in about 60 seconds.
          details: |
            # Changes:
            ${{ github.event.head_commit.message }}
          footer: Questions about the site? Found a cool app for the list? Ping @Flixbox
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm install --frozen-lockfile --force
      - name: Scrape play store data for apps
        run: npm run scrape
      - name: Build website
        run: npm run build
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Add scraped play store data

      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./build
