name: Build & Deploy 🚀
on: [push]
jobs:
  Build_and_Deploy:
    runs-on: ubuntu-latest
    env:
      USE_SSH: true
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run deploy
